"""initial schema

Revision ID: a921589b9f76
Revises: 
Create Date: 2026-10-03 10:39:03.520804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a921589b9f76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.CheckConstraint("source IN ('ui', 'agent', 'system')", name='ck_audit_log_source'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('pending_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('proposed_patch', sa.Text(), nullable=False),
    sa.Column('base_version', sa.Integer(), nullable=False),
    sa.Column('proposed_by', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'applied', 'rejected', 'expired')", name='ck_pending_changes_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirements',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("id GLOB 'REQ-[0-9][0-9][0-9]'", name='ck_requirements_id_format'),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'critical')", name='ck_requirements_priority'),
    sa.CheckConstraint("status IN ('draft', 'approved', 'implemented', 'verified', 'obsolete')", name='ck_requirements_status'),
    sa.CheckConstraint('length(trim(title)) > 0', name='ck_requirements_title_not_blank'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_items',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("id GLOB 'RISK-[0-9][0-9][0-9]'", name='ck_risk_items_id_format'),
    sa.CheckConstraint("status IN ('open', 'mitigated', 'accepted', 'closed')", name='ck_risk_items_status'),
    sa.CheckConstraint('length(trim(title)) > 0', name='ck_risk_items_title_not_blank'),
    sa.CheckConstraint('likelihood BETWEEN 1 AND 5', name='ck_risk_items_likelihood'),
    sa.CheckConstraint('severity BETWEEN 1 AND 5', name='ck_risk_items_severity'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement_risks',
    sa.Column('requirement_id', sa.String(length=16), nullable=False),
    sa.Column('risk_id', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['risk_id'], ['risk_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('requirement_id', 'risk_id')
    )
    with op.batch_alter_table('requirement_risks', schema=None) as batch_op:
        batch_op.create_index('ix_requirement_risks_risk_id', ['risk_id'], unique=False)

    op.create_table('test_cases',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('requirement_id', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("id GLOB 'TC-[0-9][0-9][0-9]'", name='ck_test_cases_id_format'),
    sa.CheckConstraint("status IN ('not_run', 'pass', 'fail', 'blocked')", name='ck_test_cases_status'),
    sa.CheckConstraint('length(trim(title)) > 0', name='ck_test_cases_title_not_blank'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.create_index('ix_test_cases_requirement_id', ['requirement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_index('ix_test_cases_requirement_id')

    op.drop_table('test_cases')
    with op.batch_alter_table('requirement_risks', schema=None) as batch_op:
        batch_op.drop_index('ix_requirement_risks_risk_id')

    op.drop_table('requirement_risks')
    op.drop_table('risk_items')
    op.drop_table('requirements')
    op.drop_table('pending_changes')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_entity')

    op.drop_table('audit_log')
    # ### end Alembic commands ###
